state_dict = {'Andaman and Nicobar Islands': 1,
 'Andhra Pradesh': 2,
 'Arunachal Pradesh': 3,
 'Assam': 4,
 'Bihar': 5,
 'Chandigarh': 6,
 'Chhattisgarh': 7,
 'Dadra and Nagar Haveli': 8,
 'Goa': 9,
 'Gujarat': 10,
 'Haryana': 11,
 'Himachal Pradesh': 12,
 'Jammu and Kashmir ': 13,
 'Jharkhand': 14,
 'Karnataka': 15,
 'Kerala': 16,
 'Madhya Pradesh': 17,
 'Maharashtra': 18,
 'Manipur': 19,
 'Meghalaya': 20,
 'Mizoram': 21,
 'Nagaland': 22,
 'Odisha': 23,
 'Puducherry': 24,
 'Punjab': 25,
 'Rajasthan': 26,
 'Sikkim': 27,
 'Tamil Nadu': 28,
 'Telangana ': 29,
 'Tripura': 30,
 'Uttar Pradesh': 31,
 'Uttarakhand': 32,
 'West Bengal': 33}

season_dict = {'Kharif': 1,
 'Whole Year ': 2,
 'Autumn     ': 3,
 'Rabi       ': 4,
 'Summer     ': 5,
 'Winter     ': 6}

crop_dict = {'Rice': 1,
 'Banana': 2,
 'Cashewnut': 3,
 'Coconut ': 4,
 'Sugarcane': 5,
 'Sweet potato': 6,
 'Dry chillies': 7,
 'Turmeric': 8,
 'Maize': 9,
 'Moong(Green Gram)': 10,
 'Urad': 11,
 'Arhar/Tur': 12,
 'Groundnut': 13,
 'Sunflower': 14,
 'Cotton(lint)': 15,
 'Jowar': 16,
 'Ragi': 17,
 'Gram': 18,
 'Wheat': 19,
 'Masoor': 20,
 'Sesamum': 21,
 'Linseed': 22,
 'Onion': 23,
 'Samai': 24,
 'Small millets': 25,
 'Coriander': 26,
 'Potato': 27,
 'Soyabean': 28,
 'Brinjal': 29,
 'Citrus Fruit': 30,
 'Grapes': 31,
 'Mango': 32,
 'Orange': 33,
 'Other Fresh Fruits': 34,
 'Other Vegetables': 35,
 'Papaya': 36,
 'Tomato': 37,
 'Rapeseed &Mustard': 38,
 'Varagu': 39,
 'Garlic': 40,
 'Ginger': 41,
 'Jute': 42,
 'Peas & beans (Pulses)': 43,
 'Blackgram': 44,
 'Paddy': 45,
 'Pineapple': 46,
 'Barley': 47,
 'Cardamom': 48,
 'Drum Stick': 49,
 'Jack Fruit': 50,
 'Tea': 51,
 'Coffee': 52,
 'Cauliflower': 53,
 'Water Melon': 54,
 'Apple': 55}

